version: 1.5.2-{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
clone_depth: 100
branches:
  # whitelist
  only:
    - master
    - develop
    - /feature\/.*/ 
  except:
    - gh-pages
environment:
  QT5: C:\Qt\5.10.0\mingw53_32
  MINGW: C:\Qt\Tools\mingw530_32
  NSIS: C:\Program Files (x86)\NSIS
  matrix:
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Debug
    TARGET: all
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Release
    TARGET: package
cache: .\build
build_script:
- cmd: >-
    set

    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

    set PATH="%NSIS%";%PATH%

    if not exist build md build

    cd .\build

    cmake -G %GENERATOR% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..

    cmake --build . --config %BUILD_TYPE% --target %TARGET%
test: off
artifacts:
- path: build\openconnect-gui*.exe
  name: openconnect-gui-1.5.2-{build}-win32.exe

